version: "3.1"

services:
  web:
    restart: always
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
    image: baldedelixo-web:dev
    working_dir: /app
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: yarn start

networks:
  app-network:
    driver: bridge
